// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPcsqVR51VDO73OjvU2l3TbchPOVrGe5M',
    appId: '1:678054838454:web:493b54c44b7fb1a6a36617',
    messagingSenderId: '678054838454',
    projectId: 'chat-app-680b8',
    authDomain: 'chat-app-680b8.firebaseapp.com',
    storageBucket: 'chat-app-680b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyt-18q3kSsjIlA0yfiEvVMF1NO7CLB3Q',
    appId: '1:678054838454:android:81c967f1a15f8886a36617',
    messagingSenderId: '678054838454',
    projectId: 'chat-app-680b8',
    storageBucket: 'chat-app-680b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtLFcZESXnn5TpnzI2yhcB3mEJov7l2FQ',
    appId: '1:678054838454:ios:ab3aa7018783d80ca36617',
    messagingSenderId: '678054838454',
    projectId: 'chat-app-680b8',
    storageBucket: 'chat-app-680b8.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtLFcZESXnn5TpnzI2yhcB3mEJov7l2FQ',
    appId: '1:678054838454:ios:ab3aa7018783d80ca36617',
    messagingSenderId: '678054838454',
    projectId: 'chat-app-680b8',
    storageBucket: 'chat-app-680b8.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPcsqVR51VDO73OjvU2l3TbchPOVrGe5M',
    appId: '1:678054838454:web:f3f6a33fc50ae94ea36617',
    messagingSenderId: '678054838454',
    projectId: 'chat-app-680b8',
    authDomain: 'chat-app-680b8.firebaseapp.com',
    storageBucket: 'chat-app-680b8.firebasestorage.app',
  );
}
